openapi: 3.0.1
info:
  title: directory-api
  description: REST API documentation for the directory-api
  version: 0.5.5-SNAPSHOT
servers:
- url: /
paths:
  /bpn-directory:
    get:
      tags:
      - BDRS Server Directory API
      description: Gets a binary gzipped stream with BPN/DID mapping entries.
      operationId: getData
      responses:
        "200":
          description: The GZipped binary stream contains BPN-to-DID mapping entries.
        "400":
          description: Request body was malformed
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
        "401":
          description: User is not authenticated
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
        "403":
          description: User is not authorized to obtain BPN/DID mapping data
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
components:
  schemas:
    ApiErrorDetail:
      type: object
      properties:
        invalidValue:
          type: object
          example: null
        message:
          type: string
          example: null
        path:
          type: string
          example: null
        type:
          type: string
          example: null
      example: null
