openapi: 3.0.1
info:
  title: directory-api
  description: REST API documentation for the directory-api
  license:
    name: "The Apache License, Version 2.0"
    url: http://www.apache.org/licenses/LICENSE-2.0.txt
  version: 0.5.8-SNAPSHOT
servers:
- url: http://localhost:8080
paths:
  /bpn-directory:
    get:
      tags:
      - BDRS Server Directory API
      description: Gets a binary gzipped stream with BPN/DID mapping entries.
      operationId: getData
      responses:
        "200":
          description: The GZipped binary stream contains BPN-to-DID mapping entries.
        "400":
          description: Request body was malformed
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
        "401":
          description: User is not authenticated
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
        "403":
          description: User is not authorized to obtain BPN/DID mapping data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
components:
  schemas:
    ApiErrorDetail:
      type: object
      properties:
        invalidValue:
          type: object
        message:
          type: string
        path:
          type: string
        type:
          type: string
      example:
        path: path
        message: message
        type: type
        invalidValue: "{}"
